### PR TITLE
Geometry rework

### PR DESCRIPTION
**Pull request by austinschneider**
The goal of these changes is to add support for more complex density models that may be needed for detectors that are not primarily composed of approximately-uniform naturally-occurring media.

I don't expect this pull request to get approved immediately, but I feel this work is now at the stage where we can work out what's left to do before we're comfortable with a merge.

This branch is now able to reproduce the same injected events as the master branch, with sub-percent differences in the injected vertex position.

### CODE REVIEW

**Comment by BenSmithers** [comment]
I'm working my way through reviewing these changes! I noticed there are a lot of files brought in from PROPOSAL too - are these now here to work with other/newer density models?

**Comment by austinschneider** [comment]
Thanks for looking through the changes @BenSmithers ! The goal of these changes is to support density models for other detectors e.g. DUNE, GVD, KM3Net, CHARM, etc. For these detectors the density model will need to include more than just the Earth+Ice/Water, and will need to support shapes beyond intersecting spherical shells. To accomplish this I decided start from PROPOSAL's geometry/density implementation and extend it to suit these needs. I believe this okay under PROPOSAL's license as long as credit is given appropriately. There probably some cruft still in some of these files that we can prune now that the necessary components are a little more clear.

Beyond what is in this pull request already, I plan to add support for rotations and an additional shape for extruded polygons, both in the short term. In the long term, I think we may want to add support for importing other geometry/density models that experiments already have on hand. You could imagine an experiment using a stripped down version of a model they are using in GEANT for example. This could be accomplished by defining the EarthModel as an interface, and then writing some thin wrappers that use the underlying geometry implementations from LeptonInjetor, GEANT, and ROOT. The main issue I see with this is that it would add some complications if we wanted to store the density model within the lic files, but that is a problem for another day.

**Comment by BenSmithers** [comment]
That all sounds great, thanks for the response! I can see that all being useful

**Comment by BenSmithers** [comment]
I've looked over all the files, and things are looking good! I liked that unit tests have been added to go along with all the new code! Ran into a few issues that might effect others when they check this out though. After checking out the branch for the first time, it appears necessary to run
```
git submodule init
git submodule update
```
so that the googletest submodule is correctly checked out. Cmake also seems to be running into an issue finding python now: 
```
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: python 
-- Found python at /usr/include/python3.8
-- Will build python!
-- Searching for python3 compatible boost_python
-- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) (found version "3.8.10")
```
It's still able to continue, but it doesn't compile the python bindings. Any ideas?

**Comment by austinschneider** [comment]
We should definitely add that extra step to the documentation now. I'm not sure if there is a graceful failure mode, i.e. tests not being compiled, when the googletest submodule is not present, but it would be nice to have in any case.

I haven't run into that issue yet myself. I'm using python 3.8.5 on Ubuntu 20.04 in my development/testing. What kind environment / setup are you using?

**Comment by BenSmithers** [comment]
I'm also on Ubuntu 20.04 and using python 3.8.10. I'll look into this and see if I'm doing something wrong

**Comment by BenSmithers** [comment]
I am thoroughly and utterly confused, but fixed the problem? Calling `cmake path/to/source` in a build directory once, then calling `make` as usual shows the above error and leads to it not compiling the pybindings for me. But, calling the same cmake command _twice_ in a build directory, and _then_ compiling has everything work flawlessly. 

The first time it both finds and doesn't find the `PythonInterp`. The second time it finds it. Unless someone else can reproduce this oddity, I'd say it's not an issue and most likely a problem specific to my machine.

**Review by BenSmithers — APPROVED** [review]
Aside from the comments previous comments, everything's looking good!

**Comment by austinschneider** [comment]
I started adding rotations to the geometry interface as well, but these features are still a work in progress.

**Pull request closed without merging**
